###################################################################

# Created by write_sdc on Tue Mar  3 17:13:57 2015

###################################################################
set sdc_version 1.8

set_units -time ns -resistance MOhm -capacitance fF -voltage V -current mA
set_driving_cell -lib_cell CND2X1 [get_ports pushin]
set_driving_cell -lib_cell CND2X1 [get_ports {cmd[1]}]
set_driving_cell -lib_cell CND2X1 [get_ports {cmd[0]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[31]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[30]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[29]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[28]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[27]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[26]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[25]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[24]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[23]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[22]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[21]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[20]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[19]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[18]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[17]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[16]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[15]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[14]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[13]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[12]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[11]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[10]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[9]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[8]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[7]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[6]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[5]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[4]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[3]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[2]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[1]}]
set_driving_cell -lib_cell CND2X1 [get_ports {q[0]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[31]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[30]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[29]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[28]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[27]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[26]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[25]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[24]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[23]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[22]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[21]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[20]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[19]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[18]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[17]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[16]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[15]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[14]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[13]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[12]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[11]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[10]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[9]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[8]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[7]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[6]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[5]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[4]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[3]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[2]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[1]}]
set_driving_cell -lib_cell CND2X1 [get_ports {h[0]}]
create_clock [get_ports clk]  -period 3.3  -waveform {0 1.65}
set_clock_uncertainty 0.25  [get_clocks clk]
set_input_delay -clock clk  0.6  [get_ports pushin]
set_input_delay -clock clk  0.6  [get_ports {cmd[1]}]
set_input_delay -clock clk  0.6  [get_ports {cmd[0]}]
set_input_delay -clock clk  0.6  [get_ports {q[31]}]
set_input_delay -clock clk  0.6  [get_ports {q[30]}]
set_input_delay -clock clk  0.6  [get_ports {q[29]}]
set_input_delay -clock clk  0.6  [get_ports {q[28]}]
set_input_delay -clock clk  0.6  [get_ports {q[27]}]
set_input_delay -clock clk  0.6  [get_ports {q[26]}]
set_input_delay -clock clk  0.6  [get_ports {q[25]}]
set_input_delay -clock clk  0.6  [get_ports {q[24]}]
set_input_delay -clock clk  0.6  [get_ports {q[23]}]
set_input_delay -clock clk  0.6  [get_ports {q[22]}]
set_input_delay -clock clk  0.6  [get_ports {q[21]}]
set_input_delay -clock clk  0.6  [get_ports {q[20]}]
set_input_delay -clock clk  0.6  [get_ports {q[19]}]
set_input_delay -clock clk  0.6  [get_ports {q[18]}]
set_input_delay -clock clk  0.6  [get_ports {q[17]}]
set_input_delay -clock clk  0.6  [get_ports {q[16]}]
set_input_delay -clock clk  0.6  [get_ports {q[15]}]
set_input_delay -clock clk  0.6  [get_ports {q[14]}]
set_input_delay -clock clk  0.6  [get_ports {q[13]}]
set_input_delay -clock clk  0.6  [get_ports {q[12]}]
set_input_delay -clock clk  0.6  [get_ports {q[11]}]
set_input_delay -clock clk  0.6  [get_ports {q[10]}]
set_input_delay -clock clk  0.6  [get_ports {q[9]}]
set_input_delay -clock clk  0.6  [get_ports {q[8]}]
set_input_delay -clock clk  0.6  [get_ports {q[7]}]
set_input_delay -clock clk  0.6  [get_ports {q[6]}]
set_input_delay -clock clk  0.6  [get_ports {q[5]}]
set_input_delay -clock clk  0.6  [get_ports {q[4]}]
set_input_delay -clock clk  0.6  [get_ports {q[3]}]
set_input_delay -clock clk  0.6  [get_ports {q[2]}]
set_input_delay -clock clk  0.6  [get_ports {q[1]}]
set_input_delay -clock clk  0.6  [get_ports {q[0]}]
set_input_delay -clock clk  0.6  [get_ports {h[31]}]
set_input_delay -clock clk  0.6  [get_ports {h[30]}]
set_input_delay -clock clk  0.6  [get_ports {h[29]}]
set_input_delay -clock clk  0.6  [get_ports {h[28]}]
set_input_delay -clock clk  0.6  [get_ports {h[27]}]
set_input_delay -clock clk  0.6  [get_ports {h[26]}]
set_input_delay -clock clk  0.6  [get_ports {h[25]}]
set_input_delay -clock clk  0.6  [get_ports {h[24]}]
set_input_delay -clock clk  0.6  [get_ports {h[23]}]
set_input_delay -clock clk  0.6  [get_ports {h[22]}]
set_input_delay -clock clk  0.6  [get_ports {h[21]}]
set_input_delay -clock clk  0.6  [get_ports {h[20]}]
set_input_delay -clock clk  0.6  [get_ports {h[19]}]
set_input_delay -clock clk  0.6  [get_ports {h[18]}]
set_input_delay -clock clk  0.6  [get_ports {h[17]}]
set_input_delay -clock clk  0.6  [get_ports {h[16]}]
set_input_delay -clock clk  0.6  [get_ports {h[15]}]
set_input_delay -clock clk  0.6  [get_ports {h[14]}]
set_input_delay -clock clk  0.6  [get_ports {h[13]}]
set_input_delay -clock clk  0.6  [get_ports {h[12]}]
set_input_delay -clock clk  0.6  [get_ports {h[11]}]
set_input_delay -clock clk  0.6  [get_ports {h[10]}]
set_input_delay -clock clk  0.6  [get_ports {h[9]}]
set_input_delay -clock clk  0.6  [get_ports {h[8]}]
set_input_delay -clock clk  0.6  [get_ports {h[7]}]
set_input_delay -clock clk  0.6  [get_ports {h[6]}]
set_input_delay -clock clk  0.6  [get_ports {h[5]}]
set_input_delay -clock clk  0.6  [get_ports {h[4]}]
set_input_delay -clock clk  0.6  [get_ports {h[3]}]
set_input_delay -clock clk  0.6  [get_ports {h[2]}]
set_input_delay -clock clk  0.6  [get_ports {h[1]}]
set_input_delay -clock clk  0.6  [get_ports {h[0]}]
set_output_delay -clock clk  0.3  [get_ports pushout]
set_output_delay -clock clk  0.3  [get_ports {z[31]}]
set_output_delay -clock clk  0.3  [get_ports {z[30]}]
set_output_delay -clock clk  0.3  [get_ports {z[29]}]
set_output_delay -clock clk  0.3  [get_ports {z[28]}]
set_output_delay -clock clk  0.3  [get_ports {z[27]}]
set_output_delay -clock clk  0.3  [get_ports {z[26]}]
set_output_delay -clock clk  0.3  [get_ports {z[25]}]
set_output_delay -clock clk  0.3  [get_ports {z[24]}]
set_output_delay -clock clk  0.3  [get_ports {z[23]}]
set_output_delay -clock clk  0.3  [get_ports {z[22]}]
set_output_delay -clock clk  0.3  [get_ports {z[21]}]
set_output_delay -clock clk  0.3  [get_ports {z[20]}]
set_output_delay -clock clk  0.3  [get_ports {z[19]}]
set_output_delay -clock clk  0.3  [get_ports {z[18]}]
set_output_delay -clock clk  0.3  [get_ports {z[17]}]
set_output_delay -clock clk  0.3  [get_ports {z[16]}]
set_output_delay -clock clk  0.3  [get_ports {z[15]}]
set_output_delay -clock clk  0.3  [get_ports {z[14]}]
set_output_delay -clock clk  0.3  [get_ports {z[13]}]
set_output_delay -clock clk  0.3  [get_ports {z[12]}]
set_output_delay -clock clk  0.3  [get_ports {z[11]}]
set_output_delay -clock clk  0.3  [get_ports {z[10]}]
set_output_delay -clock clk  0.3  [get_ports {z[9]}]
set_output_delay -clock clk  0.3  [get_ports {z[8]}]
set_output_delay -clock clk  0.3  [get_ports {z[7]}]
set_output_delay -clock clk  0.3  [get_ports {z[6]}]
set_output_delay -clock clk  0.3  [get_ports {z[5]}]
set_output_delay -clock clk  0.3  [get_ports {z[4]}]
set_output_delay -clock clk  0.3  [get_ports {z[3]}]
set_output_delay -clock clk  0.3  [get_ports {z[2]}]
set_output_delay -clock clk  0.3  [get_ports {z[1]}]
set_output_delay -clock clk  0.3  [get_ports {z[0]}]
